import { useState, useCallback } from "react";
import { Code, Monitor, Copy, Check, ChevronRight, ChevronDown, Zap, Download } from "lucide-react";
import { download } from "../lib/export.js";

export default function GenerateResults({ result, onStartNew }) {
  const [activeTab, setActiveTab] = useState("preview");
  const [copied, setCopied] = useState(false);

  if (!result) return null;

  const { scaffold, copyNotes, html } = result;

  const handleCopyHtml = useCallback(() => {
    navigator.clipboard.writeText(html).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [html]);

  const tabs = [
    { id: "preview", label: "Visual Reference", icon: Monitor },
    { id: "tree", label: "Component Tree", icon: Code },
  ];

  return (
    <div>
      {/* Copy Notes */}
      {copyNotes && (
        <div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-6">
          <p className="text-xs font-medium text-violet-700 mb-1">Copy & tone notes</p>
          <p className="text-sm text-violet-800">{copyNotes}</p>
        </div>
      )}

      {/* Tabs */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex gap-1 bg-gray-100 rounded-lg p-1 w-fit">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                activeTab === tab.id
                  ? "bg-white text-gray-900 shadow-sm"
                  : "text-gray-500 hover:text-gray-700"
              }`}
            >
              <tab.icon size={14} />
              {tab.label}
            </button>
          ))}
        </div>

        {activeTab === "preview" && html && (
          <button
            onClick={handleCopyHtml}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-gray-900 text-white hover:bg-gray-800 transition-colors"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? "Copied!" : "Copy HTML"}
          </button>
        )}
      </div>

      {/* Tab content */}
      {activeTab === "preview" && (
        <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
          {html ? (
            <iframe
              srcDoc={html}
              title="UI Reference Preview"
              className="w-full border-0"
              style={{ height: "700px" }}
              sandbox="allow-scripts"
            />
          ) : (
            <div className="p-12 text-center text-sm text-gray-400">
              No HTML preview was generated.
            </div>
          )}
        </div>
      )}

      {activeTab === "tree" && (
        <div className="bg-white rounded-xl border border-gray-200 p-5 overflow-auto" style={{ maxHeight: "700px" }}>
          {scaffold ? (
            <TreeNode node={scaffold} depth={0} />
          ) : (
            <div className="p-12 text-center text-sm text-gray-400">
              No component tree was generated.
            </div>
          )}
        </div>
      )}

      {/* Action bar */}
      <div className="mt-8 flex items-center justify-between gap-3">
        <button
          onClick={onStartNew}
          className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm text-gray-600 hover:bg-gray-100 transition-colors"
        >
          <Zap size={16} /> Start New Generation
        </button>
        <div className="flex items-center gap-2">
          {html && (
            <button
              onClick={() => {
                const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
                download(`designlens-ui-${stamp}.html`, html, "text/html");
              }}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium text-gray-700 bg-white border border-gray-200 hover:bg-gray-50"
            >
              <Download size={14} /> HTML
            </button>
          )}
          {scaffold && (
            <button
              onClick={() => {
                const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
                download(
                  `designlens-scaffold-${stamp}.json`,
                  JSON.stringify({ scaffold, copyNotes }, null, 2),
                  "application/json"
                );
              }}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium text-gray-700 bg-white border border-gray-200 hover:bg-gray-50"
            >
              <Download size={14} /> JSON
            </button>
          )}
          <div className="hidden sm:block text-xs text-gray-400 ml-1">
            Generated by 3 AI agents
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Collapsible tree node component ───

function TreeNode({ node, depth }) {
  const [expanded, setExpanded] = useState(depth < 2);
  const hasChildren = node.children && node.children.length > 0;

  const variantColors = {
    primary: "bg-blue-100 text-blue-700",
    secondary: "bg-gray-100 text-gray-700",
    danger: "bg-red-100 text-red-700",
    ghost: "bg-gray-50 text-gray-600",
  };

  return (
    <div className={depth > 0 ? "ml-4 border-l border-gray-100 pl-3" : ""}>
      <div
        className="flex items-start gap-2 py-1.5 group cursor-pointer hover:bg-gray-50 rounded px-1 -mx-1"
        onClick={() => hasChildren && setExpanded(!expanded)}
      >
        {hasChildren ? (
          expanded ? (
            <ChevronDown size={14} className="text-gray-400 mt-0.5 flex-shrink-0" />
          ) : (
            <ChevronRight size={14} className="text-gray-400 mt-0.5 flex-shrink-0" />
          )
        ) : (
          <span className="w-3.5 flex-shrink-0" />
        )}

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-sm font-mono font-semibold text-indigo-600">
              {node.component}
            </span>
            {node.props && Object.keys(node.props).length > 0 && (
              <span className="text-xs text-gray-400 font-mono truncate">
                {Object.entries(node.props)
                  .slice(0, 3)
                  .map(([k, v]) => `${k}=${JSON.stringify(v)}`)
                  .join(" ")}
                {Object.keys(node.props).length > 3 && " ..."}
              </span>
            )}
          </div>
          {node.notes && (
            <p className="text-xs text-gray-500 mt-0.5">{node.notes}</p>
          )}
        </div>
      </div>

      {expanded && hasChildren && (
        <div>
          {node.children.map((child, i) => (
            <TreeNode key={i} node={child} depth={depth + 1} />
          ))}
        </div>
      )}
    </div>
  );
}
